/*
 * Twilio - Accounts
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`create_credential_public_key`]
#[derive(Clone, Debug)]
pub struct CreateCredentialPublicKeyParams {
    /// A URL encoded representation of the public key. For example, `-----BEGIN PUBLIC KEY-----MIIBIjANB.pa9xQIDAQAB-----END PUBLIC KEY-----`
    pub public_key: String,
    /// A descriptive string that you create to describe the resource. It can be up to 64 characters long.
    pub friendly_name: Option<String>,
    /// The SID of the Subaccount that this Credential should be associated with. Must be a valid Subaccount of the account issuing the request
    pub account_sid: Option<String>,
}

/// struct for passing parameters to the method [`delete_credential_public_key`]
#[derive(Clone, Debug)]
pub struct DeleteCredentialPublicKeyParams {
    /// The Twilio-provided string that uniquely identifies the PublicKey resource to delete.
    pub sid: String,
}

/// struct for passing parameters to the method [`fetch_credential_public_key`]
#[derive(Clone, Debug)]
pub struct FetchCredentialPublicKeyParams {
    /// The Twilio-provided string that uniquely identifies the PublicKey resource to fetch.
    pub sid: String,
}

/// struct for passing parameters to the method [`list_credential_public_key`]
#[derive(Clone, Debug)]
pub struct ListCredentialPublicKeyParams {
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<i64>,
    /// The page index. This value is simply for client state.
    pub page: Option<i32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>,
}

/// struct for passing parameters to the method [`update_credential_public_key`]
#[derive(Clone, Debug)]
pub struct UpdateCredentialPublicKeyParams {
    /// The Twilio-provided string that uniquely identifies the PublicKey resource to update.
    pub sid: String,
    /// A descriptive string that you create to describe the resource. It can be up to 64 characters long.
    pub friendly_name: Option<String>,
}

/// struct for typed successes of method [`create_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCredentialPublicKeySuccess {
    Status201(models::AccountsPeriodV1PeriodCredentialPeriodCredentialPublicKey),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`delete_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteCredentialPublicKeySuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`fetch_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchCredentialPublicKeySuccess {
    Status200(models::AccountsPeriodV1PeriodCredentialPeriodCredentialPublicKey),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`list_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCredentialPublicKeySuccess {
    Status200(models::ListCredentialPublicKeyResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`update_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCredentialPublicKeySuccess {
    Status200(models::AccountsPeriodV1PeriodCredentialPeriodCredentialPublicKey),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCredentialPublicKeyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteCredentialPublicKeyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchCredentialPublicKeyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCredentialPublicKeyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_credential_public_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCredentialPublicKeyError {
    UnknownValue(serde_json::Value),
}

/// Create a new Public Key Credential
pub async fn create_credential_public_key(
    configuration: &configuration::Configuration,
    params: CreateCredentialPublicKeyParams,
) -> Result<ResponseContent<CreateCredentialPublicKeySuccess>, Error<CreateCredentialPublicKeyError>>
{
    let uri_str = format!("{}/v1/Credentials/PublicKeys", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("PublicKey", params.public_key.to_string());
    if let Some(param_value) = params.friendly_name {
        multipart_form_params.insert("FriendlyName", param_value.to_string());
    }
    if let Some(param_value) = params.account_sid {
        multipart_form_params.insert("AccountSid", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        let entity: Option<CreateCredentialPublicKeySuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateCredentialPublicKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete a Credential from your account
pub async fn delete_credential_public_key(
    configuration: &configuration::Configuration,
    params: DeleteCredentialPublicKeyParams,
) -> Result<ResponseContent<DeleteCredentialPublicKeySuccess>, Error<DeleteCredentialPublicKeyError>>
{
    let uri_str = format!(
        "{}/v1/Credentials/PublicKeys/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        let entity: Option<DeleteCredentialPublicKeySuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteCredentialPublicKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Fetch the public key specified by the provided Credential Sid
pub async fn fetch_credential_public_key(
    configuration: &configuration::Configuration,
    params: FetchCredentialPublicKeyParams,
) -> Result<ResponseContent<FetchCredentialPublicKeySuccess>, Error<FetchCredentialPublicKeyError>>
{
    let uri_str = format!(
        "{}/v1/Credentials/PublicKeys/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        let entity: Option<FetchCredentialPublicKeySuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchCredentialPublicKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a collection of Public Key Credentials belonging to the account used to make the request
pub async fn list_credential_public_key(
    configuration: &configuration::Configuration,
    params: ListCredentialPublicKeyParams,
) -> Result<ResponseContent<ListCredentialPublicKeySuccess>, Error<ListCredentialPublicKeyError>> {
    let uri_str = format!("{}/v1/Credentials/PublicKeys", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        let entity: Option<ListCredentialPublicKeySuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCredentialPublicKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Modify the properties of a given Account
pub async fn update_credential_public_key(
    configuration: &configuration::Configuration,
    params: UpdateCredentialPublicKeyParams,
) -> Result<ResponseContent<UpdateCredentialPublicKeySuccess>, Error<UpdateCredentialPublicKeyError>>
{
    let uri_str = format!(
        "{}/v1/Credentials/PublicKeys/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    if let Some(param_value) = params.friendly_name {
        multipart_form_params.insert("FriendlyName", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        let entity: Option<UpdateCredentialPublicKeySuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateCredentialPublicKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
