/*
 * Twilio - Accounts
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountsPeriodV1PeriodSafelist {
    /// The unique string that we created to identify the SafeList resource.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The phone number or phone number 1k prefix in SafeList.
    #[serde(
        rename = "phone_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
}

impl AccountsPeriodV1PeriodSafelist {
    pub fn new() -> AccountsPeriodV1PeriodSafelist {
        AccountsPeriodV1PeriodSafelist {
            sid: None,
            phone_number: None,
        }
    }
}
