/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodFeedback {
    /// The Assistant ID.
    #[serde(rename = "assistant_id")]
    pub assistant_id: String,
    /// The Feedback ID.
    #[serde(rename = "id")]
    pub id: String,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Feedback.
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The SID of the User created the Feedback.
    #[serde(rename = "user_sid", skip_serializing_if = "Option::is_none")]
    pub user_sid: Option<String>,
    /// The Message ID.
    #[serde(rename = "message_id")]
    pub message_id: String,
    /// The Score to provide as Feedback (0-1)
    #[serde(rename = "score")]
    pub score: f32,
    /// The Session ID.
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// The text to be given as feedback.
    #[serde(rename = "text")]
    pub text: String,
    /// The date and time in GMT when the Feedback was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_created")]
    pub date_created: String,
    /// The date and time in GMT when the Feedback was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_updated")]
    pub date_updated: String,
}

impl AssistantsPeriodV1PeriodServicePeriodFeedback {
    pub fn new(assistant_id: String, id: String, message_id: String, score: f32, session_id: String, text: String, date_created: String, date_updated: String) -> AssistantsPeriodV1PeriodServicePeriodFeedback {
        AssistantsPeriodV1PeriodServicePeriodFeedback {
            assistant_id,
            id,
            account_sid: None,
            user_sid: None,
            message_id,
            score,
            session_id,
            text,
            date_created,
            date_updated,
        }
    }
}

