/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodSegmentCredential {
    /// The profile API key.
    #[serde(rename = "profile_api_key", skip_serializing_if = "Option::is_none")]
    pub profile_api_key: Option<String>,
    /// The space ID.
    #[serde(rename = "space_id", skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    /// The write key.
    #[serde(rename = "write_key", skip_serializing_if = "Option::is_none")]
    pub write_key: Option<String>,
}

impl AssistantsPeriodV1PeriodServicePeriodSegmentCredential {
    pub fn new() -> AssistantsPeriodV1PeriodServicePeriodSegmentCredential {
        AssistantsPeriodV1PeriodServicePeriodSegmentCredential {
            profile_api_key: None,
            space_id: None,
            write_key: None,
        }
    }
}

