/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodCreateFeedbackRequest {
    /// The message ID.
    #[serde(rename = "message_id", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
    /// The score to be given(0-1).
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    /// The Session ID.
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// The text to be given as feedback.
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

impl AssistantsPeriodV1PeriodServicePeriodCreateFeedbackRequest {
    pub fn new(session_id: String) -> AssistantsPeriodV1PeriodServicePeriodCreateFeedbackRequest {
        AssistantsPeriodV1PeriodServicePeriodCreateFeedbackRequest {
            message_id: None,
            score: None,
            session_id,
            text: None,
        }
    }
}

