/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodCreatePolicyRequest {
    /// The description of the policy.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The Policy ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the policy.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "policy_details", deserialize_with = "Option::deserialize")]
    pub policy_details: Option<serde_json::Value>,
    /// The description of the policy.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl AssistantsPeriodV1PeriodServicePeriodCreatePolicyRequest {
    pub fn new(policy_details: Option<serde_json::Value>) -> AssistantsPeriodV1PeriodServicePeriodCreatePolicyRequest {
        AssistantsPeriodV1PeriodServicePeriodCreatePolicyRequest {
            description: None,
            id: None,
            name: None,
            policy_details,
            r#type: None,
        }
    }
}

