/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageResponse {
    /// success or failure based on whether the request successfully generated a response.
    #[serde(rename = "status")]
    pub status: String,
    /// If successful, this property will denote whether the response was flagged or not.
    #[serde(rename = "flagged", skip_serializing_if = "Option::is_none")]
    pub flagged: Option<bool>,
    /// This property will denote whether the request was aborted or not.
    #[serde(rename = "aborted", skip_serializing_if = "Option::is_none")]
    pub aborted: Option<bool>,
    /// The unique name for the session.
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that sent the Message.
    #[serde(rename = "account_sid")]
    pub account_sid: String,
    /// If successful, the body of the generated response
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// The error message if generation was not successful
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageResponse {
    pub fn new(status: String, session_id: String, account_sid: String) -> AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageResponse {
        AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageResponse {
            status,
            flagged: None,
            aborted: None,
            session_id,
            account_sid,
            body: None,
            error: None,
        }
    }
}

