/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodTool {
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Tool resource.
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The description of the tool.
    #[serde(rename = "description")]
    pub description: String,
    /// True if the tool is enabled.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// The tool ID.
    #[serde(rename = "id")]
    pub id: String,
    /// The metadata related to method, url, input_schema to used with the Tool.
    #[serde(rename = "meta")]
    pub meta: serde_json::Value,
    /// The name of the tool.
    #[serde(rename = "name")]
    pub name: String,
    /// The authentication requirement for the tool.
    #[serde(rename = "requires_auth")]
    pub requires_auth: bool,
    /// The type of the tool. ('WEBHOOK')
    #[serde(rename = "type")]
    pub r#type: String,
    /// The url of the tool resource.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The date and time in GMT when the Tool was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_created")]
    pub date_created: String,
    /// The date and time in GMT when the Tool was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_updated")]
    pub date_updated: String,
}

impl AssistantsPeriodV1PeriodServicePeriodTool {
    pub fn new(description: String, enabled: bool, id: String, meta: serde_json::Value, name: String, requires_auth: bool, r#type: String, date_created: String, date_updated: String) -> AssistantsPeriodV1PeriodServicePeriodTool {
        AssistantsPeriodV1PeriodServicePeriodTool {
            account_sid: None,
            description,
            enabled,
            id,
            meta,
            name,
            requires_auth,
            r#type,
            url: None,
            date_created,
            date_updated,
        }
    }
}

