/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageRequest {
    /// The unique identity of user for the session.
    #[serde(rename = "identity")]
    pub identity: String,
    /// The unique name for the session.
    #[serde(rename = "session_id", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// The query to ask the assistant.
    #[serde(rename = "body")]
    pub body: String,
    /// The webhook url to call after the assistant has generated a response or report an error.
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
    /// one of the modes 'chat', 'email' or 'voice'
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
}

impl AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageRequest {
    pub fn new(identity: String, body: String) -> AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageRequest {
        AssistantsPeriodV1PeriodServicePeriodAssistantSendMessageRequest {
            identity,
            session_id: None,
            body,
            webhook: None,
            mode: None,
        }
    }
}

