/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodCreateAssistantRequest {
    #[serde(rename = "customer_ai", skip_serializing_if = "Option::is_none")]
    pub customer_ai: Option<Box<models::AssistantsPeriodV1PeriodServicePeriodCustomerAi>>,
    /// The name of the assistant.
    #[serde(rename = "name")]
    pub name: String,
    /// The owner/company of the assistant.
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// The personality prompt to be used for assistant.
    #[serde(rename = "personality_prompt", skip_serializing_if = "Option::is_none")]
    pub personality_prompt: Option<String>,
    #[serde(rename = "segment_credential", skip_serializing_if = "Option::is_none")]
    pub segment_credential: Option<Box<models::AssistantsPeriodV1PeriodServicePeriodSegmentCredential>>,
}

impl AssistantsPeriodV1PeriodServicePeriodCreateAssistantRequest {
    pub fn new(name: String) -> AssistantsPeriodV1PeriodServicePeriodCreateAssistantRequest {
        AssistantsPeriodV1PeriodServicePeriodCreateAssistantRequest {
            customer_ai: None,
            name,
            owner: None,
            personality_prompt: None,
            segment_credential: None,
        }
    }
}

