/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodUpdateToolRequest {
    /// The Assistant ID.
    #[serde(rename = "assistant_id", skip_serializing_if = "Option::is_none")]
    pub assistant_id: Option<String>,
    /// The description of the tool.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// True if the tool is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// The metadata related to method, url, input_schema to used with the Tool.
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
    /// The name of the tool.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Box<models::AssistantsPeriodV1PeriodServicePeriodCreatePolicyRequest>>,
    /// The type of the tool.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl AssistantsPeriodV1PeriodServicePeriodUpdateToolRequest {
    pub fn new() -> AssistantsPeriodV1PeriodServicePeriodUpdateToolRequest {
        AssistantsPeriodV1PeriodServicePeriodUpdateToolRequest {
            assistant_id: None,
            description: None,
            enabled: None,
            meta: None,
            name: None,
            policy: None,
            r#type: None,
        }
    }
}

