/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodPolicy {
    /// The Policy ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the policy.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description of the policy.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Policy resource.
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The SID of the User that created the Policy resource.
    #[serde(rename = "user_sid", skip_serializing_if = "Option::is_none")]
    pub user_sid: Option<String>,
    /// The type of the policy.
    #[serde(rename = "type")]
    pub r#type: String,
    /// The details of the policy based on the type.
    #[serde(rename = "policy_details")]
    pub policy_details: serde_json::Value,
    /// The date and time in GMT when the Policy was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The date and time in GMT when the Policy was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
}

impl AssistantsPeriodV1PeriodServicePeriodPolicy {
    pub fn new(r#type: String, policy_details: serde_json::Value) -> AssistantsPeriodV1PeriodServicePeriodPolicy {
        AssistantsPeriodV1PeriodServicePeriodPolicy {
            id: None,
            name: None,
            description: None,
            account_sid: None,
            user_sid: None,
            r#type,
            policy_details,
            date_created: None,
            date_updated: None,
        }
    }
}

