/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodCustomerAi {
    /// True if the perception engine is enabled.
    #[serde(rename = "perception_engine_enabled")]
    pub perception_engine_enabled: bool,
    /// True if the personalization engine is enabled.
    #[serde(rename = "personalization_engine_enabled")]
    pub personalization_engine_enabled: bool,
}

impl AssistantsPeriodV1PeriodServicePeriodCustomerAi {
    pub fn new(perception_engine_enabled: bool, personalization_engine_enabled: bool) -> AssistantsPeriodV1PeriodServicePeriodCustomerAi {
        AssistantsPeriodV1PeriodServicePeriodCustomerAi {
            perception_engine_enabled,
            personalization_engine_enabled,
        }
    }
}

