/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantsPeriodV1PeriodServicePeriodCreateToolRequest {
    /// The Assistant ID.
    #[serde(rename = "assistant_id", skip_serializing_if = "Option::is_none")]
    pub assistant_id: Option<String>,
    /// The description of the tool.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// True if the tool is enabled.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// The metadata related to method, url, input_schema to used with the Tool.
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
    /// The name of the tool.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Box<models::AssistantsPeriodV1PeriodServicePeriodCreatePolicyRequest>>,
    /// The description of the tool.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AssistantsPeriodV1PeriodServicePeriodCreateToolRequest {
    pub fn new(enabled: bool, name: String, r#type: String) -> AssistantsPeriodV1PeriodServicePeriodCreateToolRequest {
        AssistantsPeriodV1PeriodServicePeriodCreateToolRequest {
            assistant_id: None,
            description: None,
            enabled,
            meta: None,
            name,
            policy: None,
            r#type,
        }
    }
}

