/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListKnowledgeResponse {
    #[serde(rename = "knowledge", skip_serializing_if = "Option::is_none")]
    pub knowledge: Option<Vec<models::AssistantsPeriodV1PeriodServicePeriodKnowledge>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAssistantResponseMeta>>,
}

impl ListKnowledgeResponse {
    pub fn new() -> ListKnowledgeResponse {
        ListKnowledgeResponse {
            knowledge: None,
            meta: None,
        }
    }
}

