/*
 * Twilio - Assistants
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListKnowledgeChunksResponse {
    #[serde(rename = "chunks", skip_serializing_if = "Option::is_none")]
    pub chunks: Option<Vec<models::AssistantsPeriodV1PeriodServicePeriodKnowledgeChunk>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAssistantResponseMeta>>,
}

impl ListKnowledgeChunksResponse {
    pub fn new() -> ListKnowledgeChunksResponse {
        ListKnowledgeChunksResponse {
            chunks: None,
            meta: None,
        }
    }
}

