/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`create_siprec`]
#[derive(Clone, Debug)]
pub struct CreateSiprecParams {
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created this Siprec resource.
    pub account_sid: String,
    /// The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) the Siprec resource is associated with.
    pub call_sid: String,
    /// The user-specified name of this Siprec, if one was given when the Siprec was created. This may be used to stop the Siprec.
    pub name: Option<String>,
    /// Unique name used when configuring the connector via Marketplace Add-on.
    pub connector_name: Option<String>,
    pub track: Option<models::SiprecEnumTrack>,
    /// Absolute URL of the status callback.
    pub status_callback: Option<String>,
    /// The http method for the status_callback (one of GET, POST).
    pub status_callback_method: Option<String>,
    /// Parameter name
    pub parameter1_period_name: Option<String>,
    /// Parameter value
    pub parameter1_period_value: Option<String>,
    /// Parameter name
    pub parameter2_period_name: Option<String>,
    /// Parameter value
    pub parameter2_period_value: Option<String>,
    /// Parameter name
    pub parameter3_period_name: Option<String>,
    /// Parameter value
    pub parameter3_period_value: Option<String>,
    /// Parameter name
    pub parameter4_period_name: Option<String>,
    /// Parameter value
    pub parameter4_period_value: Option<String>,
    /// Parameter name
    pub parameter5_period_name: Option<String>,
    /// Parameter value
    pub parameter5_period_value: Option<String>,
    /// Parameter name
    pub parameter6_period_name: Option<String>,
    /// Parameter value
    pub parameter6_period_value: Option<String>,
    /// Parameter name
    pub parameter7_period_name: Option<String>,
    /// Parameter value
    pub parameter7_period_value: Option<String>,
    /// Parameter name
    pub parameter8_period_name: Option<String>,
    /// Parameter value
    pub parameter8_period_value: Option<String>,
    /// Parameter name
    pub parameter9_period_name: Option<String>,
    /// Parameter value
    pub parameter9_period_value: Option<String>,
    /// Parameter name
    pub parameter10_period_name: Option<String>,
    /// Parameter value
    pub parameter10_period_value: Option<String>,
    /// Parameter name
    pub parameter11_period_name: Option<String>,
    /// Parameter value
    pub parameter11_period_value: Option<String>,
    /// Parameter name
    pub parameter12_period_name: Option<String>,
    /// Parameter value
    pub parameter12_period_value: Option<String>,
    /// Parameter name
    pub parameter13_period_name: Option<String>,
    /// Parameter value
    pub parameter13_period_value: Option<String>,
    /// Parameter name
    pub parameter14_period_name: Option<String>,
    /// Parameter value
    pub parameter14_period_value: Option<String>,
    /// Parameter name
    pub parameter15_period_name: Option<String>,
    /// Parameter value
    pub parameter15_period_value: Option<String>,
    /// Parameter name
    pub parameter16_period_name: Option<String>,
    /// Parameter value
    pub parameter16_period_value: Option<String>,
    /// Parameter name
    pub parameter17_period_name: Option<String>,
    /// Parameter value
    pub parameter17_period_value: Option<String>,
    /// Parameter name
    pub parameter18_period_name: Option<String>,
    /// Parameter value
    pub parameter18_period_value: Option<String>,
    /// Parameter name
    pub parameter19_period_name: Option<String>,
    /// Parameter value
    pub parameter19_period_value: Option<String>,
    /// Parameter name
    pub parameter20_period_name: Option<String>,
    /// Parameter value
    pub parameter20_period_value: Option<String>,
    /// Parameter name
    pub parameter21_period_name: Option<String>,
    /// Parameter value
    pub parameter21_period_value: Option<String>,
    /// Parameter name
    pub parameter22_period_name: Option<String>,
    /// Parameter value
    pub parameter22_period_value: Option<String>,
    /// Parameter name
    pub parameter23_period_name: Option<String>,
    /// Parameter value
    pub parameter23_period_value: Option<String>,
    /// Parameter name
    pub parameter24_period_name: Option<String>,
    /// Parameter value
    pub parameter24_period_value: Option<String>,
    /// Parameter name
    pub parameter25_period_name: Option<String>,
    /// Parameter value
    pub parameter25_period_value: Option<String>,
    /// Parameter name
    pub parameter26_period_name: Option<String>,
    /// Parameter value
    pub parameter26_period_value: Option<String>,
    /// Parameter name
    pub parameter27_period_name: Option<String>,
    /// Parameter value
    pub parameter27_period_value: Option<String>,
    /// Parameter name
    pub parameter28_period_name: Option<String>,
    /// Parameter value
    pub parameter28_period_value: Option<String>,
    /// Parameter name
    pub parameter29_period_name: Option<String>,
    /// Parameter value
    pub parameter29_period_value: Option<String>,
    /// Parameter name
    pub parameter30_period_name: Option<String>,
    /// Parameter value
    pub parameter30_period_value: Option<String>,
    /// Parameter name
    pub parameter31_period_name: Option<String>,
    /// Parameter value
    pub parameter31_period_value: Option<String>,
    /// Parameter name
    pub parameter32_period_name: Option<String>,
    /// Parameter value
    pub parameter32_period_value: Option<String>,
    /// Parameter name
    pub parameter33_period_name: Option<String>,
    /// Parameter value
    pub parameter33_period_value: Option<String>,
    /// Parameter name
    pub parameter34_period_name: Option<String>,
    /// Parameter value
    pub parameter34_period_value: Option<String>,
    /// Parameter name
    pub parameter35_period_name: Option<String>,
    /// Parameter value
    pub parameter35_period_value: Option<String>,
    /// Parameter name
    pub parameter36_period_name: Option<String>,
    /// Parameter value
    pub parameter36_period_value: Option<String>,
    /// Parameter name
    pub parameter37_period_name: Option<String>,
    /// Parameter value
    pub parameter37_period_value: Option<String>,
    /// Parameter name
    pub parameter38_period_name: Option<String>,
    /// Parameter value
    pub parameter38_period_value: Option<String>,
    /// Parameter name
    pub parameter39_period_name: Option<String>,
    /// Parameter value
    pub parameter39_period_value: Option<String>,
    /// Parameter name
    pub parameter40_period_name: Option<String>,
    /// Parameter value
    pub parameter40_period_value: Option<String>,
    /// Parameter name
    pub parameter41_period_name: Option<String>,
    /// Parameter value
    pub parameter41_period_value: Option<String>,
    /// Parameter name
    pub parameter42_period_name: Option<String>,
    /// Parameter value
    pub parameter42_period_value: Option<String>,
    /// Parameter name
    pub parameter43_period_name: Option<String>,
    /// Parameter value
    pub parameter43_period_value: Option<String>,
    /// Parameter name
    pub parameter44_period_name: Option<String>,
    /// Parameter value
    pub parameter44_period_value: Option<String>,
    /// Parameter name
    pub parameter45_period_name: Option<String>,
    /// Parameter value
    pub parameter45_period_value: Option<String>,
    /// Parameter name
    pub parameter46_period_name: Option<String>,
    /// Parameter value
    pub parameter46_period_value: Option<String>,
    /// Parameter name
    pub parameter47_period_name: Option<String>,
    /// Parameter value
    pub parameter47_period_value: Option<String>,
    /// Parameter name
    pub parameter48_period_name: Option<String>,
    /// Parameter value
    pub parameter48_period_value: Option<String>,
    /// Parameter name
    pub parameter49_period_name: Option<String>,
    /// Parameter value
    pub parameter49_period_value: Option<String>,
    /// Parameter name
    pub parameter50_period_name: Option<String>,
    /// Parameter value
    pub parameter50_period_value: Option<String>,
    /// Parameter name
    pub parameter51_period_name: Option<String>,
    /// Parameter value
    pub parameter51_period_value: Option<String>,
    /// Parameter name
    pub parameter52_period_name: Option<String>,
    /// Parameter value
    pub parameter52_period_value: Option<String>,
    /// Parameter name
    pub parameter53_period_name: Option<String>,
    /// Parameter value
    pub parameter53_period_value: Option<String>,
    /// Parameter name
    pub parameter54_period_name: Option<String>,
    /// Parameter value
    pub parameter54_period_value: Option<String>,
    /// Parameter name
    pub parameter55_period_name: Option<String>,
    /// Parameter value
    pub parameter55_period_value: Option<String>,
    /// Parameter name
    pub parameter56_period_name: Option<String>,
    /// Parameter value
    pub parameter56_period_value: Option<String>,
    /// Parameter name
    pub parameter57_period_name: Option<String>,
    /// Parameter value
    pub parameter57_period_value: Option<String>,
    /// Parameter name
    pub parameter58_period_name: Option<String>,
    /// Parameter value
    pub parameter58_period_value: Option<String>,
    /// Parameter name
    pub parameter59_period_name: Option<String>,
    /// Parameter value
    pub parameter59_period_value: Option<String>,
    /// Parameter name
    pub parameter60_period_name: Option<String>,
    /// Parameter value
    pub parameter60_period_value: Option<String>,
    /// Parameter name
    pub parameter61_period_name: Option<String>,
    /// Parameter value
    pub parameter61_period_value: Option<String>,
    /// Parameter name
    pub parameter62_period_name: Option<String>,
    /// Parameter value
    pub parameter62_period_value: Option<String>,
    /// Parameter name
    pub parameter63_period_name: Option<String>,
    /// Parameter value
    pub parameter63_period_value: Option<String>,
    /// Parameter name
    pub parameter64_period_name: Option<String>,
    /// Parameter value
    pub parameter64_period_value: Option<String>,
    /// Parameter name
    pub parameter65_period_name: Option<String>,
    /// Parameter value
    pub parameter65_period_value: Option<String>,
    /// Parameter name
    pub parameter66_period_name: Option<String>,
    /// Parameter value
    pub parameter66_period_value: Option<String>,
    /// Parameter name
    pub parameter67_period_name: Option<String>,
    /// Parameter value
    pub parameter67_period_value: Option<String>,
    /// Parameter name
    pub parameter68_period_name: Option<String>,
    /// Parameter value
    pub parameter68_period_value: Option<String>,
    /// Parameter name
    pub parameter69_period_name: Option<String>,
    /// Parameter value
    pub parameter69_period_value: Option<String>,
    /// Parameter name
    pub parameter70_period_name: Option<String>,
    /// Parameter value
    pub parameter70_period_value: Option<String>,
    /// Parameter name
    pub parameter71_period_name: Option<String>,
    /// Parameter value
    pub parameter71_period_value: Option<String>,
    /// Parameter name
    pub parameter72_period_name: Option<String>,
    /// Parameter value
    pub parameter72_period_value: Option<String>,
    /// Parameter name
    pub parameter73_period_name: Option<String>,
    /// Parameter value
    pub parameter73_period_value: Option<String>,
    /// Parameter name
    pub parameter74_period_name: Option<String>,
    /// Parameter value
    pub parameter74_period_value: Option<String>,
    /// Parameter name
    pub parameter75_period_name: Option<String>,
    /// Parameter value
    pub parameter75_period_value: Option<String>,
    /// Parameter name
    pub parameter76_period_name: Option<String>,
    /// Parameter value
    pub parameter76_period_value: Option<String>,
    /// Parameter name
    pub parameter77_period_name: Option<String>,
    /// Parameter value
    pub parameter77_period_value: Option<String>,
    /// Parameter name
    pub parameter78_period_name: Option<String>,
    /// Parameter value
    pub parameter78_period_value: Option<String>,
    /// Parameter name
    pub parameter79_period_name: Option<String>,
    /// Parameter value
    pub parameter79_period_value: Option<String>,
    /// Parameter name
    pub parameter80_period_name: Option<String>,
    /// Parameter value
    pub parameter80_period_value: Option<String>,
    /// Parameter name
    pub parameter81_period_name: Option<String>,
    /// Parameter value
    pub parameter81_period_value: Option<String>,
    /// Parameter name
    pub parameter82_period_name: Option<String>,
    /// Parameter value
    pub parameter82_period_value: Option<String>,
    /// Parameter name
    pub parameter83_period_name: Option<String>,
    /// Parameter value
    pub parameter83_period_value: Option<String>,
    /// Parameter name
    pub parameter84_period_name: Option<String>,
    /// Parameter value
    pub parameter84_period_value: Option<String>,
    /// Parameter name
    pub parameter85_period_name: Option<String>,
    /// Parameter value
    pub parameter85_period_value: Option<String>,
    /// Parameter name
    pub parameter86_period_name: Option<String>,
    /// Parameter value
    pub parameter86_period_value: Option<String>,
    /// Parameter name
    pub parameter87_period_name: Option<String>,
    /// Parameter value
    pub parameter87_period_value: Option<String>,
    /// Parameter name
    pub parameter88_period_name: Option<String>,
    /// Parameter value
    pub parameter88_period_value: Option<String>,
    /// Parameter name
    pub parameter89_period_name: Option<String>,
    /// Parameter value
    pub parameter89_period_value: Option<String>,
    /// Parameter name
    pub parameter90_period_name: Option<String>,
    /// Parameter value
    pub parameter90_period_value: Option<String>,
    /// Parameter name
    pub parameter91_period_name: Option<String>,
    /// Parameter value
    pub parameter91_period_value: Option<String>,
    /// Parameter name
    pub parameter92_period_name: Option<String>,
    /// Parameter value
    pub parameter92_period_value: Option<String>,
    /// Parameter name
    pub parameter93_period_name: Option<String>,
    /// Parameter value
    pub parameter93_period_value: Option<String>,
    /// Parameter name
    pub parameter94_period_name: Option<String>,
    /// Parameter value
    pub parameter94_period_value: Option<String>,
    /// Parameter name
    pub parameter95_period_name: Option<String>,
    /// Parameter value
    pub parameter95_period_value: Option<String>,
    /// Parameter name
    pub parameter96_period_name: Option<String>,
    /// Parameter value
    pub parameter96_period_value: Option<String>,
    /// Parameter name
    pub parameter97_period_name: Option<String>,
    /// Parameter value
    pub parameter97_period_value: Option<String>,
    /// Parameter name
    pub parameter98_period_name: Option<String>,
    /// Parameter value
    pub parameter98_period_value: Option<String>,
    /// Parameter name
    pub parameter99_period_name: Option<String>,
    /// Parameter value
    pub parameter99_period_value: Option<String>,
}

/// struct for passing parameters to the method [`update_siprec`]
#[derive(Clone, Debug)]
pub struct UpdateSiprecParams {
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created this Siprec resource.
    pub account_sid: String,
    /// The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) the Siprec resource is associated with.
    pub call_sid: String,
    /// The SID of the Siprec resource, or the `name` used when creating the resource
    pub sid: String,
    pub status: models::SiprecEnumUpdateStatus,
}

/// struct for typed successes of method [`create_siprec`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateSiprecSuccess {
    Status200(models::ApiPeriodV2010PeriodAccountPeriodCallPeriodSiprec),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`update_siprec`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateSiprecSuccess {
    Status200(models::ApiPeriodV2010PeriodAccountPeriodCallPeriodSiprec),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_siprec`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateSiprecError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_siprec`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateSiprecError {
    UnknownValue(serde_json::Value),
}

/// Create a Siprec
pub async fn create_siprec(
    configuration: &configuration::Configuration,
    params: CreateSiprecParams,
) -> Result<ResponseContent<CreateSiprecSuccess>, Error<CreateSiprecError>> {
    let uri_str = format!(
        "{}/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec.json",
        configuration.base_path,
        AccountSid = crate::apis::urlencode(params.account_sid),
        CallSid = crate::apis::urlencode(params.call_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    if let Some(param_value) = params.name {
        multipart_form_params.insert("Name", param_value.to_string());
    }
    if let Some(param_value) = params.connector_name {
        multipart_form_params.insert("ConnectorName", param_value.to_string());
    }
    if let Some(param_value) = params.track {
        multipart_form_params.insert("Track", param_value.to_string());
    }
    if let Some(param_value) = params.status_callback {
        multipart_form_params.insert("StatusCallback", param_value.to_string());
    }
    if let Some(param_value) = params.status_callback_method {
        multipart_form_params.insert("StatusCallbackMethod", param_value.to_string());
    }
    if let Some(param_value) = params.parameter1_period_name {
        multipart_form_params.insert("Parameter1.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter1_period_value {
        multipart_form_params.insert("Parameter1.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter2_period_name {
        multipart_form_params.insert("Parameter2.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter2_period_value {
        multipart_form_params.insert("Parameter2.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter3_period_name {
        multipart_form_params.insert("Parameter3.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter3_period_value {
        multipart_form_params.insert("Parameter3.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter4_period_name {
        multipart_form_params.insert("Parameter4.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter4_period_value {
        multipart_form_params.insert("Parameter4.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter5_period_name {
        multipart_form_params.insert("Parameter5.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter5_period_value {
        multipart_form_params.insert("Parameter5.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter6_period_name {
        multipart_form_params.insert("Parameter6.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter6_period_value {
        multipart_form_params.insert("Parameter6.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter7_period_name {
        multipart_form_params.insert("Parameter7.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter7_period_value {
        multipart_form_params.insert("Parameter7.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter8_period_name {
        multipart_form_params.insert("Parameter8.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter8_period_value {
        multipart_form_params.insert("Parameter8.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter9_period_name {
        multipart_form_params.insert("Parameter9.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter9_period_value {
        multipart_form_params.insert("Parameter9.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter10_period_name {
        multipart_form_params.insert("Parameter10.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter10_period_value {
        multipart_form_params.insert("Parameter10.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter11_period_name {
        multipart_form_params.insert("Parameter11.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter11_period_value {
        multipart_form_params.insert("Parameter11.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter12_period_name {
        multipart_form_params.insert("Parameter12.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter12_period_value {
        multipart_form_params.insert("Parameter12.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter13_period_name {
        multipart_form_params.insert("Parameter13.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter13_period_value {
        multipart_form_params.insert("Parameter13.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter14_period_name {
        multipart_form_params.insert("Parameter14.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter14_period_value {
        multipart_form_params.insert("Parameter14.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter15_period_name {
        multipart_form_params.insert("Parameter15.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter15_period_value {
        multipart_form_params.insert("Parameter15.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter16_period_name {
        multipart_form_params.insert("Parameter16.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter16_period_value {
        multipart_form_params.insert("Parameter16.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter17_period_name {
        multipart_form_params.insert("Parameter17.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter17_period_value {
        multipart_form_params.insert("Parameter17.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter18_period_name {
        multipart_form_params.insert("Parameter18.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter18_period_value {
        multipart_form_params.insert("Parameter18.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter19_period_name {
        multipart_form_params.insert("Parameter19.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter19_period_value {
        multipart_form_params.insert("Parameter19.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter20_period_name {
        multipart_form_params.insert("Parameter20.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter20_period_value {
        multipart_form_params.insert("Parameter20.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter21_period_name {
        multipart_form_params.insert("Parameter21.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter21_period_value {
        multipart_form_params.insert("Parameter21.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter22_period_name {
        multipart_form_params.insert("Parameter22.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter22_period_value {
        multipart_form_params.insert("Parameter22.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter23_period_name {
        multipart_form_params.insert("Parameter23.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter23_period_value {
        multipart_form_params.insert("Parameter23.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter24_period_name {
        multipart_form_params.insert("Parameter24.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter24_period_value {
        multipart_form_params.insert("Parameter24.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter25_period_name {
        multipart_form_params.insert("Parameter25.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter25_period_value {
        multipart_form_params.insert("Parameter25.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter26_period_name {
        multipart_form_params.insert("Parameter26.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter26_period_value {
        multipart_form_params.insert("Parameter26.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter27_period_name {
        multipart_form_params.insert("Parameter27.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter27_period_value {
        multipart_form_params.insert("Parameter27.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter28_period_name {
        multipart_form_params.insert("Parameter28.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter28_period_value {
        multipart_form_params.insert("Parameter28.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter29_period_name {
        multipart_form_params.insert("Parameter29.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter29_period_value {
        multipart_form_params.insert("Parameter29.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter30_period_name {
        multipart_form_params.insert("Parameter30.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter30_period_value {
        multipart_form_params.insert("Parameter30.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter31_period_name {
        multipart_form_params.insert("Parameter31.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter31_period_value {
        multipart_form_params.insert("Parameter31.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter32_period_name {
        multipart_form_params.insert("Parameter32.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter32_period_value {
        multipart_form_params.insert("Parameter32.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter33_period_name {
        multipart_form_params.insert("Parameter33.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter33_period_value {
        multipart_form_params.insert("Parameter33.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter34_period_name {
        multipart_form_params.insert("Parameter34.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter34_period_value {
        multipart_form_params.insert("Parameter34.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter35_period_name {
        multipart_form_params.insert("Parameter35.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter35_period_value {
        multipart_form_params.insert("Parameter35.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter36_period_name {
        multipart_form_params.insert("Parameter36.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter36_period_value {
        multipart_form_params.insert("Parameter36.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter37_period_name {
        multipart_form_params.insert("Parameter37.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter37_period_value {
        multipart_form_params.insert("Parameter37.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter38_period_name {
        multipart_form_params.insert("Parameter38.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter38_period_value {
        multipart_form_params.insert("Parameter38.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter39_period_name {
        multipart_form_params.insert("Parameter39.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter39_period_value {
        multipart_form_params.insert("Parameter39.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter40_period_name {
        multipart_form_params.insert("Parameter40.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter40_period_value {
        multipart_form_params.insert("Parameter40.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter41_period_name {
        multipart_form_params.insert("Parameter41.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter41_period_value {
        multipart_form_params.insert("Parameter41.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter42_period_name {
        multipart_form_params.insert("Parameter42.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter42_period_value {
        multipart_form_params.insert("Parameter42.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter43_period_name {
        multipart_form_params.insert("Parameter43.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter43_period_value {
        multipart_form_params.insert("Parameter43.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter44_period_name {
        multipart_form_params.insert("Parameter44.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter44_period_value {
        multipart_form_params.insert("Parameter44.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter45_period_name {
        multipart_form_params.insert("Parameter45.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter45_period_value {
        multipart_form_params.insert("Parameter45.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter46_period_name {
        multipart_form_params.insert("Parameter46.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter46_period_value {
        multipart_form_params.insert("Parameter46.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter47_period_name {
        multipart_form_params.insert("Parameter47.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter47_period_value {
        multipart_form_params.insert("Parameter47.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter48_period_name {
        multipart_form_params.insert("Parameter48.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter48_period_value {
        multipart_form_params.insert("Parameter48.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter49_period_name {
        multipart_form_params.insert("Parameter49.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter49_period_value {
        multipart_form_params.insert("Parameter49.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter50_period_name {
        multipart_form_params.insert("Parameter50.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter50_period_value {
        multipart_form_params.insert("Parameter50.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter51_period_name {
        multipart_form_params.insert("Parameter51.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter51_period_value {
        multipart_form_params.insert("Parameter51.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter52_period_name {
        multipart_form_params.insert("Parameter52.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter52_period_value {
        multipart_form_params.insert("Parameter52.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter53_period_name {
        multipart_form_params.insert("Parameter53.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter53_period_value {
        multipart_form_params.insert("Parameter53.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter54_period_name {
        multipart_form_params.insert("Parameter54.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter54_period_value {
        multipart_form_params.insert("Parameter54.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter55_period_name {
        multipart_form_params.insert("Parameter55.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter55_period_value {
        multipart_form_params.insert("Parameter55.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter56_period_name {
        multipart_form_params.insert("Parameter56.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter56_period_value {
        multipart_form_params.insert("Parameter56.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter57_period_name {
        multipart_form_params.insert("Parameter57.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter57_period_value {
        multipart_form_params.insert("Parameter57.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter58_period_name {
        multipart_form_params.insert("Parameter58.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter58_period_value {
        multipart_form_params.insert("Parameter58.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter59_period_name {
        multipart_form_params.insert("Parameter59.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter59_period_value {
        multipart_form_params.insert("Parameter59.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter60_period_name {
        multipart_form_params.insert("Parameter60.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter60_period_value {
        multipart_form_params.insert("Parameter60.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter61_period_name {
        multipart_form_params.insert("Parameter61.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter61_period_value {
        multipart_form_params.insert("Parameter61.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter62_period_name {
        multipart_form_params.insert("Parameter62.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter62_period_value {
        multipart_form_params.insert("Parameter62.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter63_period_name {
        multipart_form_params.insert("Parameter63.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter63_period_value {
        multipart_form_params.insert("Parameter63.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter64_period_name {
        multipart_form_params.insert("Parameter64.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter64_period_value {
        multipart_form_params.insert("Parameter64.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter65_period_name {
        multipart_form_params.insert("Parameter65.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter65_period_value {
        multipart_form_params.insert("Parameter65.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter66_period_name {
        multipart_form_params.insert("Parameter66.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter66_period_value {
        multipart_form_params.insert("Parameter66.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter67_period_name {
        multipart_form_params.insert("Parameter67.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter67_period_value {
        multipart_form_params.insert("Parameter67.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter68_period_name {
        multipart_form_params.insert("Parameter68.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter68_period_value {
        multipart_form_params.insert("Parameter68.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter69_period_name {
        multipart_form_params.insert("Parameter69.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter69_period_value {
        multipart_form_params.insert("Parameter69.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter70_period_name {
        multipart_form_params.insert("Parameter70.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter70_period_value {
        multipart_form_params.insert("Parameter70.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter71_period_name {
        multipart_form_params.insert("Parameter71.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter71_period_value {
        multipart_form_params.insert("Parameter71.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter72_period_name {
        multipart_form_params.insert("Parameter72.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter72_period_value {
        multipart_form_params.insert("Parameter72.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter73_period_name {
        multipart_form_params.insert("Parameter73.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter73_period_value {
        multipart_form_params.insert("Parameter73.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter74_period_name {
        multipart_form_params.insert("Parameter74.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter74_period_value {
        multipart_form_params.insert("Parameter74.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter75_period_name {
        multipart_form_params.insert("Parameter75.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter75_period_value {
        multipart_form_params.insert("Parameter75.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter76_period_name {
        multipart_form_params.insert("Parameter76.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter76_period_value {
        multipart_form_params.insert("Parameter76.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter77_period_name {
        multipart_form_params.insert("Parameter77.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter77_period_value {
        multipart_form_params.insert("Parameter77.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter78_period_name {
        multipart_form_params.insert("Parameter78.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter78_period_value {
        multipart_form_params.insert("Parameter78.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter79_period_name {
        multipart_form_params.insert("Parameter79.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter79_period_value {
        multipart_form_params.insert("Parameter79.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter80_period_name {
        multipart_form_params.insert("Parameter80.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter80_period_value {
        multipart_form_params.insert("Parameter80.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter81_period_name {
        multipart_form_params.insert("Parameter81.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter81_period_value {
        multipart_form_params.insert("Parameter81.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter82_period_name {
        multipart_form_params.insert("Parameter82.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter82_period_value {
        multipart_form_params.insert("Parameter82.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter83_period_name {
        multipart_form_params.insert("Parameter83.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter83_period_value {
        multipart_form_params.insert("Parameter83.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter84_period_name {
        multipart_form_params.insert("Parameter84.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter84_period_value {
        multipart_form_params.insert("Parameter84.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter85_period_name {
        multipart_form_params.insert("Parameter85.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter85_period_value {
        multipart_form_params.insert("Parameter85.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter86_period_name {
        multipart_form_params.insert("Parameter86.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter86_period_value {
        multipart_form_params.insert("Parameter86.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter87_period_name {
        multipart_form_params.insert("Parameter87.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter87_period_value {
        multipart_form_params.insert("Parameter87.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter88_period_name {
        multipart_form_params.insert("Parameter88.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter88_period_value {
        multipart_form_params.insert("Parameter88.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter89_period_name {
        multipart_form_params.insert("Parameter89.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter89_period_value {
        multipart_form_params.insert("Parameter89.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter90_period_name {
        multipart_form_params.insert("Parameter90.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter90_period_value {
        multipart_form_params.insert("Parameter90.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter91_period_name {
        multipart_form_params.insert("Parameter91.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter91_period_value {
        multipart_form_params.insert("Parameter91.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter92_period_name {
        multipart_form_params.insert("Parameter92.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter92_period_value {
        multipart_form_params.insert("Parameter92.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter93_period_name {
        multipart_form_params.insert("Parameter93.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter93_period_value {
        multipart_form_params.insert("Parameter93.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter94_period_name {
        multipart_form_params.insert("Parameter94.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter94_period_value {
        multipart_form_params.insert("Parameter94.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter95_period_name {
        multipart_form_params.insert("Parameter95.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter95_period_value {
        multipart_form_params.insert("Parameter95.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter96_period_name {
        multipart_form_params.insert("Parameter96.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter96_period_value {
        multipart_form_params.insert("Parameter96.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter97_period_name {
        multipart_form_params.insert("Parameter97.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter97_period_value {
        multipart_form_params.insert("Parameter97.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter98_period_name {
        multipart_form_params.insert("Parameter98.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter98_period_value {
        multipart_form_params.insert("Parameter98.Value", param_value.to_string());
    }
    if let Some(param_value) = params.parameter99_period_name {
        multipart_form_params.insert("Parameter99.Name", param_value.to_string());
    }
    if let Some(param_value) = params.parameter99_period_value {
        multipart_form_params.insert("Parameter99.Value", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        let entity: Option<CreateSiprecSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateSiprecError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Stop a Siprec using either the SID of the Siprec resource or the `name` used when creating the resource
pub async fn update_siprec(
    configuration: &configuration::Configuration,
    params: UpdateSiprecParams,
) -> Result<ResponseContent<UpdateSiprecSuccess>, Error<UpdateSiprecError>> {
    let uri_str = format!(
        "{}/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec/{Sid}.json",
        configuration.base_path,
        AccountSid = crate::apis::urlencode(params.account_sid),
        CallSid = crate::apis::urlencode(params.call_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("Status", params.status.to_string());
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        let entity: Option<UpdateSiprecSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateSiprecError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
